#if !canImport(ObjectiveC)
    import XCTest

    extension DangerSwiftJiraGitHubTests {
        // DO NOT MODIFY: This is autogenerated, use:
        //   `swift test --generate-linuxmain`
        // to regenerate.
        static let __allTests__DangerSwiftJiraGitHubTests = [
            ("testDoNotSkipJiraInPullRequest", testDoNotSkipJiraInPullRequest),
            ("testFindJiraIssueInPullRequestBody", testFindJiraIssueInPullRequestBody),
            ("testFindJiraIssueInPullRequestCommits", testFindJiraIssueInPullRequestCommits),
            ("testFindJiraIssueInPullRequestTitle", testFindJiraIssueInPullRequestTitle),
            ("testGenerateJiraLink", testGenerateJiraLink),
            ("testOnlyFindUniqueIssues", testOnlyFindUniqueIssues),
            ("testSkipJiraInPullRequest", testSkipJiraInPullRequest),
        ]
    }

    public func __allTests() -> [XCTestCaseEntry] {
        [
            testCase(DangerSwiftJiraGitHubTests.__allTests__DangerSwiftJiraGitHubTests),
        ]
    }
#endif
