#if !canImport(ObjectiveC)
import XCTest

extension DangerSwiftJiraTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DangerSwiftJiraTests = [
        ("testDummy", testDummy),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(DangerSwiftJiraTests.__allTests__DangerSwiftJiraTests),
    ]
}
#endif
