---
name: Update Release Draft

on:
  workflow_dispatch:

  push:
    branches:
      - master

jobs:
  update_release_draft:
    name: Update Release Draft
    runs-on: ubuntu-latest
    steps:
      - name: Release Draft
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release_drafter_config.yml

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
