name: Master Branch Verification

on:
  workflow_dispatch:

  push:
    branches:
      - master

jobs:
  linux:
    runs-on: ubuntu-latest
    name: 🐧 Linux Test
    steps:
      - uses: actions/checkout@v2
      - name: Test
        uses: ./.github/actions/test-verify-action
        with:
          include-coverage: false

  macos:
    runs-on: macos-11
    name:  MacOS Test
    steps:
      - uses: actions/checkout@v2
      - name: Test & Coverage
        uses: ./.github/actions/test-verify-action
        with:
          include-coverage: true
        env:
          danger-token: ${{ secrets.DANGER_SWIFT_GITHUB_TOKEN }}

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
